export type { GatePaintOptions, GateSeed } from "./core/index.js";
export type {
  GateCrest,
  GateFamily,
  GateFrameController,
  GateFrameErrorCode,
  GateFrameStatus,
  GateGenerationVersion,
  GateGeometry,
  GateGeometryV1,
  GateGeometryV2,
  GateGeometryV3,
  GateOptions,
  GateOptionsV1,
  GateOptionsV2,
  GateOptionsV3,
  GateOptionUpdate,
  GateSnapshot,
  GateSnapshotBase,
  GateSnapshotV1,
  GateSnapshotV2,
  GateSnapshotV3,
} from "./dom/index.js";
export {
  GateFrameAlreadyMountedError,
  GateFrameDestroyedError,
  GateFrameError,
  GateFrameInsufficientSpaceError,
  GateFrameInvalidOptionsError,
  GateFrameInvalidSelectorError,
  GateFrameNotReadyError,
  GateFramePositioningConflictError,
  GateFrameTargetNotFoundError,
  GateFrameTargetNotHTMLElementError,
  GateFrameUnsupportedDimensionsError,
  GateFrameUnsupportedTargetError,
  gateFrame,
} from "./dom/index.js";
